Repository Fork-N-Forge/Python-Sala, pull requests merged in 2023-10, with the labels that each got.

#16 Expense Tracker
  Expense Tracker/Readme.md
  Expense Tracker/expense.py
Labels: good first issue, hacktoberfest2023, hacktoberfest, opensource

#15 Create URL Shortener
  URL Shortener
Labels: hacktoberfest2023, hacktoberfest, opensource

#14 Create Weather App
  Weather App
Labels: hacktoberfest2023, hacktoberfest, opensource

#19 Added password manager
  Password Manager
Labels: hacktoberfest2023, hacktoberfest, opensource

#11 Weather App using Open Weather
  WeatherApp.py
Labels: hacktoberfest2023, hacktoberfest, opensource

#17 Create Chat Application
  Chat Application
Labels: hacktoberfest2023, hacktoberfest, opensource

#22 Added the code under Hackotberfest 2023
  Library Managment/Library.py
Labels: hacktoberfest2023, hacktoberfest

#21 Python script to resize the image
  Image_resizer/image_resizer.py
  Image_resizer/images/pixyworld10.jpg
  Image_resizer/images/pixyworld11.jpg
  Image_resizer/images/pixyworld12.jpg
  Image_resizer/images/pixyworld13.jpg
  Image_resizer/images/pixyworld14.jpg
  Image_resizer/images/pixyworld5.jpg
  Image_resizer/images/pixyworld6.jpg
  Image_resizer/images/pixyworld7.jpg
  Image_resizer/images/pixyworld8.jpg
  Image_resizer/images/pixyworld9.jpg
Labels: hacktoberfest2023, hacktoberfest

#20 Added code in password manager file
  Password Manager
Labels: hacktoberfest2023, hacktoberfest

#32 Add Banking system
  Banking_system/banking.py
Labels: hacktoberfest2023, hacktoberfest

#37 Made calculator using tkinter library
  Calculator/main.py
Labels: hacktoberfest-accepted, hacktoberfest

#36 Added a password manager
  Password-manager/main.py
  Password-manager/mykey.key
Labels: hacktoberfest-accepted, hacktoberfest

#31 added gui with a pie chart features to visualize the expenses
  Expense Tracker/Readme.md
  Expense Tracker/expense.py
Labels: hacktoberfest-accepted, hacktoberfest

#30 Complete modification of Gui interface
  WeatherApp.py
  logo.png
  logo2.png
  search_icon.png
Labels: hacktoberfest-accepted, hacktoberfest

#39 Added a Chat Application Using Python
  Chat Application Python/Readme.md
  Chat Application Python/chat_client.py
  Chat Application Python/chat_server.py
Labels: hacktoberfest-accepted, hacktoberfest

#41 Added Web Scraper Using Python
  Web Scraper/Readme.md
  Web Scraper/web_scraping.py
Labels: hacktoberfest-accepted, hacktoberfest

#43 Added Maze game
  Maze Game/game.py
Labels: hacktoberfest-accepted, hacktoberfest

#44 Added todo with gui
  Todo_with_GUI/to_do_app.py
Labels: hacktoberfest-accepted, hacktoberfest

#46 Added Flask web app for OpenAI-based Resume-JD matching and rating.
  AI-Resume-Rating/Readme.md
  AI-Resume-Rating/main.py
  AI-Resume-Rating/templates/index.html
  AI-Resume-Rating/templates/resutl.html
Labels: hacktoberfest-accepted, hacktoberfest

#49 addedcode
  pdf_to_doc/Crud_in_flask/__pycache__/main.cpython-310.pyc
  pdf_to_doc/Crud_in_flask/create_db.py
  pdf_to_doc/Crud_in_flask/database.sql
  pdf_to_doc/Crud_in_flask/main.py
  pdf_to_doc/Crud_in_flask/static/styles/style.css
  pdf_to_doc/Crud_in_flask/templates/base.html
  pdf_to_doc/Crud_in_flask/templates/create.html
  pdf_to_doc/Crud_in_flask/templates/edit.html
  pdf_to_doc/Crud_in_flask/templates/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#51 Currency Converter
  Image-Generator/Currency_Converter/README.md
  Image-Generator/Currency_Converter/currency-converter.py
Labels: hacktoberfest-accepted, hacktoberfest

#53 Add files via upload
  Chinese_FlashCard/README.md
  Chinese_FlashCard/app/app.py
  Chinese_FlashCard/app/config.json
  Chinese_FlashCard/app/main.py
  Chinese_FlashCard/app/models.py
  Chinese_FlashCard/dragon.png
  Chinese_FlashCard/myapp.png
Labels: hacktoberfest-accepted, hacktoberfest

#54 Color game in python
  Color_Game/README.md
  Color_Game/highest_score.txt
  Color_Game/main.py
Labels: hacktoberfest-accepted, hacktoberfest

#55 email slicer code in python
  Email Slicer/EmailSlicer.py
  Email Slicer/README.md
Labels: hacktoberfest-accepted, hacktoberfest
